Repository lightning/bolts, pull requests merged in 2019-02, with the labels that each got.

#558 Specify OP_DATA to express accepted/offered_htlc_script with same
  03-transactions.md
Labels: spelling

#559 Clarify ownership of max_htlc limits at receiving update_add_htlc
  02-peer-protocol.md
Labels: spelling

#563 BOLT 4: Correct "16-byte" to "12-byte" (padding)
  04-onion-routing.md
Labels: 2019-02-04, spelling

#562 Rephrase Forwarding HTLCs Requirements
  02-peer-protocol.md
Labels: 2019-02-04, spelling

#556 fix broken links
  08-transport.md
Labels: spelling

#573 BOLT 2: fix sentence in introduction of chapter `Channel Establishment`
  02-peer-protocol.md
Labels: spelling

#570 BOLT 4: fix onion test vectors
  04-onion-routing.md
Labels: 2019-02-18
