Repository lightning/bolts, pull requests merged in 2020-02, with the labels that each got.

#684 BOLT 7: be more aggressive about sending our own gossip.
  07-routing-gossip.md
Labels: Meeting Discussion

#741 Fix a typo in `insert_secret` pseudo code
  03-transactions.md
Labels: spelling

#742 Remove reference to DER encoding for public keys in compressed format
  02-peer-protocol.md
  03-transactions.md
  04-onion-routing.md
  08-transport.md
Labels: clarification

#596 Single-option large channel proposal
  02-peer-protocol.md
  09-features.md
Labels: Meeting Discussion

#682 BOLT 1: add networks to init message.
  01-messaging.md
  07-routing-gossip.md
Labels: Awaiting Interop, Meeting Discussion

#547 Keep HMAC case consistent
  04-onion-routing.md
Labels: spelling

#743 Clarify numerical comparison of pubkeys
  .aspell.en.pws
  03-transactions.md
  07-routing-gossip.md
Labels: clarification

#747 [BOLT11] Feature Bits MUST be required
  11-payment-encoding.md
Labels: clarification

#714 Bolt 1: Specify that extensions to existing messages must use TLV
  01-messaging.md
  02-peer-protocol.md
Labels: Meeting Discussion
