Repository lightning/bolts, pull requests merged in 2020-01, with the labels that each got.

#723 Resolve two spec oddities regarding new features.
  07-routing-gossip.md
  09-features.md
Labels: Meeting Discussion, clarification

#725 BOLT09: fix incorrect hyperlink text for option_mpp
  09-features.md
Labels: spelling

#722 04-onion-routing.md: Fix factual error about `final_expiry_too_soon`.
  04-onion-routing.md
Labels: Meeting Discussion, clarification

#705 BOLT 1: Define custom message type range
  01-messaging.md
Labels: Meeting Discussion

#732 Update 01-messaging.md
  01-messaging.md
Labels: spelling

#700 Specify that resolution of amount is msat
  11-payment-encoding.md
Labels: Meeting Discussion, clarification

#733 Fix bad wording of amount requirement in Bolt11
  11-payment-encoding.md
Labels: spelling
